version: '3.8'


services:
  netcatcher:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    init: true # Required for crond to work
    image: netcatcher:${VERSION:-latest}
    privileged: true
    env_file:
      - .env
    volumes:
      - pcap_data:/pcap_data
      - ./logs:/var/log/

volumes:
  pcap_data:
    name: pcap_data
